### ISSUE TITLE
Bookmarklet and browser extensions

### ISSUE THREAD

**Issue by meetbryce** [wooorm/alex#32] opened 2015-09-08 03:29 UTC

**Comment by wooorm** [comment] 2015-09-08 07:58
@meetbryce Could you describe what you want this to do?

**Comment by meetbryce** [comment] 2015-09-08 08:29
Would be good to be able to highlight text and then activate the
bookmarklet and have the AlexJS results come up in a modal window.

The use cases I'm imagining are:
- emails
- google docs
- blog posts

On Tue, Sep 8, 2015 at 5:58 PM Titus Wormer <notifications@github.com>
wrote:

> @meetbryce <https://github.com/meetbryce> Could you describe what you
> want this to do?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/wooorm/alex/issues/32#issuecomment-138467623>.
>
-- 
Cheers,
Bryce York

**Comment by wooorm** [comment] 2015-09-09 10:29
I sure would like this but am not interested in creating them myself.

**Comment by meetbryce** [comment] 2015-09-09 10:33
I'll look into it once I've gotten some practice with Alex. Hopefully I'll
be able to figure out a way to print it together.

Will pull request my fork if it makes sense to incorporate it in the main
repo.
On Wed, 9 Sep 2015 at 8:29 pm, Titus Wormer <notifications@github.com>
wrote:

> I sure would like this but am not interested in creating them myself.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/wooorm/alex/issues/32#issuecomment-138867455>.
>
-- 
Cheers,
Bryce York

**Comment by wooorm** [comment] 2015-09-09 10:50
@meetbryce Wouldn’t it be a lot easier to create a separate repo?
In it, a `bookmarklet.js` which loads `alex.min.js` (if no `window.alex`), gets the selected text, runs alex (`var res = alex(text).messages`), and displays it? (`console.log(res.map(String))`)

**Comment by danielhickman** [comment] 2015-09-12 03:27
I have some experience with Chrome extensions. I'll will take a look at the code and attempt when I have a chance.

**Comment by wooorm** [comment] 2015-09-12 07:56
@danielhickman Cool :+1:

**Comment by sean-roberts** [comment] 2015-09-14 21:00
Yep I am all about seeing an extension come to life with this

**Comment by wooorm** [comment] 2015-09-15 10:25
@sean-roberts Cool! :+1:

@danielhickman were you able to investigate this?

**Comment by danielhickman** [comment] 2015-09-16 04:15
It might take me a while. I'm fairly new.

**Comment by wooorm** [comment] 2015-09-16 08:26
Okay, no problem. I’m not sure what “a while” means, I’m guessing others can also try their had at making an extension?

**Comment by danielhickman** [comment] 2015-09-16 14:25
Apologies for being vague. Do you have an idea on how you'd like it to operate?
Should it:
- The extension and bookmarklet act the same?
- Query the whole page and open that in a new panel window
- Query `contentEditable` and inputs
- See what page is open and perform a different task?

I can try to do all of these, but it'd take me a while to get settings working correctly in a Chrome Extension.

**Comment by danielhickman** [comment] 2015-09-16 15:06
After looking into the bookmarklet, Alex itself has more than 11 lines for every character allowed in Chrome's bookmarklets. So I had to use something like this instead:
```javascript
var alexScript= document.createElement('script');
alexScript.setAttribute('src','https://raw.githubusercontent.com/wooorm/alex/master/alex.js');
document.head.appendChild(alexScript);

alert(alex('We’ve confirmed his his his his identity.').messages);
```
Which doesn't work on everything from GitHub to Gmail because of the uber popular Content Security Policy directive regarding the sources of scripts loaded.

So it doesn't look easy to get it working in a bookmarklet. There's two ways that still work with Chrome extensions though.

**Comment by wooorm** [comment] 2015-09-16 15:45
@danielhickman Cool, thanks for taking the time to look into it!

*   I don’t really care about a bookmarklet myself. I think extensions would be easiest;
*   I suggest looking at the selected text and running that through alex;

Did you say you have experience with Chrome Extensions? Also, I’d suggest using npm and browserify or duo as a driver for the repo of the extension. Are you experienced with node/npm/browserify/duo?

I prefer those because that makes it easier to keep the extension up-to-date, plus it makes it easier for me to help :smile:

**Comment by danielhickman** [comment] 2015-09-16 16:14
I've used node and npm but not browserify duo and not experienced with any of them. There is a simple solution which is a webhook to a script on a server (I can have it set up in a minute or two on mine) that auto updates it (and allows the Webstore to use that as the update). I'm assuming npm would work somewhat like that too.

Anyways, I have a Chrome dummy extension that has a local copy of Alex.JS. You press the browser action and it alerts `alex('We’ve confirmed his identity.').messages`. I'll setup using selection as input and probably a styled output in a new panel window or something.

https://github.com/danielhickman/Alex-Chrome-Extension

**Comment by wooorm** [comment] 2015-09-16 18:26
Nice! Looking forward to when you’ve got that covered. Make sure to ping me if you need help :)

**Comment by sean-roberts** [comment] 2015-09-16 18:28
I have experience making extensions as well. I agree though, npm / commonJS including Alex.JS would make it easier to maintain what version is supported and keeps it more explicit. Also, hosting it on another server would incur the http call for loading the library in. As we know, the fastest request is one we don't have to make, so including the library with your extension code would make more sense from a performance perspective as well.

**Comment by wooorm** [comment] 2015-09-16 18:29
@sean-roberts :+1:

**Comment by danielhickman** [comment] 2015-09-16 19:59
@sean-roberts I'm not sure how npm works with Chrome extensions. Does it work with ones hosted on the Chrome webstore?

**Comment by sean-roberts** [comment] 2015-09-16 21:26
So really what I was saying is use npm as a your package management and use something like browserify in your build process to pull in your dependent modules -- in this case, Alex.JS.

**Comment by meetbryce** [comment] 2015-09-16 23:26
Also, hosting it on a server could potentially end up being a bottleneck if
this thing gets super popular - which I think is totally possible.

So excited to see this come to life!
On Thu, 17 Sep 2015 at 7:26 am, Sean Roberts <notifications@github.com>
wrote:

> So really what I was saying is use npm as a your package management and
> use something like browserify in your build process to pull in your
> dependent modules -- in this case, Alex.JS.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/wooorm/alex/issues/32#issuecomment-140899551>.
>
-- 
Cheers,
Bryce York

**Comment by danielhickman** [comment] 2015-09-17 07:12
Do you mean using the `updateurl` in the manifest would create a bottle neck?

**Comment by meetbryce** [comment] 2015-09-17 07:41
I meant having the code hosting on a remote server rather than on the users
local machine, sorry.

Just considering someone would need to manage hosting if they chose to go
that route.
On Thu, 17 Sep 2015 at 5:12 PM, Daniel Hickman <notifications@github.com>
wrote:

> Do you mean using the updateurl in the manifest would create a bottle
> neck?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/wooorm/alex/issues/32#issuecomment-140989160>.
>
-- 
Cheers,
Bryce York

**Comment by danielhickman** [comment] 2015-09-19 00:20
I've done a lot of work on the Chrome extension. It's fully functional and uses your selected text or inputted text (like the demo on alexjs.com). I've used similar code too. I'm working on the overlay on the input (I used a div with contenteditable instead of and textarea because of the overlay that has a few visual bugs (will make issues for them). 

I'm also don't know exactly what #43 is caused by, but it's occurring in my modified version too.

**Comment by wooorm** [comment] 2015-09-19 07:25
@danielhickman Great to hear its working! Have you pushed to `danielhickman/Alex-Chrome-Extension`? The reason for asking is because the docs are pretty “minimal”. I’d like to make it really easy for people to download the extension, so I’d prefer to update the docs.

For a Chrome Extension example, check out [github-linker](https://github.com/github-linker/chrome-extension)’s chrome extension. For some alex examples, see the [list of integrations](https://github.com/wooorm/alex#integrations).

**Comment by danielhickman** [comment] 2015-09-19 14:06
@wooorm Haven't pushed docs yet. I've been trying to finish up the look first. :smile:

**Comment by wooorm** [comment] 2015-09-19 14:09
Okay, awesome, let me know if you need my opinion on things :)

**Comment by danielhickman** [comment] 2015-09-20 02:56
@wooorm @meetbryce I have completed it with exception of it auto updating alex.js and the issue highlight.

I welcome any feedback :smile: 

Download: https://github.com/danielhickman/Alex-Chrome-Extension/releases/tag/v0.1

**Comment by wooorm** [comment] 2015-09-20 08:40
@danielhickman Oh wow that looks wonderful! Works very well too!

![screen shot 2015-09-20 at 10 24 18 a m](https://cloud.githubusercontent.com/assets/944406/9979842/cbecc5dc-5f81-11e5-8117-c5292d88ad88.png)

Congrats on the work. It’s so awesome :smile: 

Some minor nitpicks:

*   The headings in the licenses list are a bit funky (e.g., `Javscript & CSS`), maybe the can be omitted, or
    less obtrusive by making them grey instead of purple?
*   `Javscript & CSS` >  `Javascript & CSS`;
*   There’s a little more spacing under the `Issues` block than there is on the sides, I’d go for the same size on every side if possible!
*   It’s a bit weird that the caret starts at the beginning of the selected text (`|We’ve confirmed...` instead of `...his identity|`)
*   Maybe rename `AlexJS` in the hamburger menu to `Website` (that way people know where they’re going);
*   Rename Alex, where it refers to the project (not to the site), to just `alex` (note the case);
*   Maybe, instead of having both `License: MIT License` in the subtitle and `LICENSE` in the bottom button bar, opt for `MIT License` only, and in the button bar?

Other than that, the points you mentioned above (auto-updating and issue-highlight), just the docs on GH.

Again, very well done!

**Comment by sindresorhus** [comment] 2015-09-20 08:51
> `Javscript & CSS > Javascript & CSS;`.

Actually: `JavaScript & CSS;`

-

Looks good, though I was hoping for something that integrated with any `<textarea>`. That way I could have it run directly when writing comments on GitHub and other websites. Like the [Grammarly](https://chrome.google.com/webstore/detail/grammarly-spell-checker-g/kbfnbcaeplbcioakkpcpgfkobkghlhen?hl=en) and [Markdown Here](http://markdown-here.com/) Chrome extensions.

**Comment by wooorm** [comment] 2015-09-20 08:52
@sindresorhus Oh whoops, your right :grimacing:

**Comment by wooorm** [comment] 2015-09-20 09:01
@sindresorhus @danielhickman Didn’t know about Grammarly before. Basically, it places a counter on a textarea and pulls writing through the program, displaying the number of issues. Then, you can click on that counter to open up an editor (like the `Alex` panel). That could work here too!

**Comment by sindresorhus** [comment] 2015-09-20 09:07
@wooorm It also marks words inline in the textarea.

**Comment by wooorm** [comment] 2015-09-20 09:15
@sindresorhus I couldn’t get that to work on GitHub, I can on Gmail though. Maybe it only works for content-editable-type input? Interesting :)

**Comment by sindresorhus** [comment] 2015-09-20 09:29
@wooorm It used to highlight the words on GitHub, but that stopped working some weeks ago. It still does show a popup if you hover over an incorrect word, though.

**Comment by danielhickman** [comment] 2015-09-20 16:17
@wooorm 
>-The headings in the licenses list are a bit funky (e.g., Javscript & CSS), maybe the can be omitted, or less obtrusive by making them grey instead of purple?
-Javscript & CSS > Javascript & CSS;
-There’s a little more spacing under the Issues block than there is on the sides, I’d go for the same size on every side if possible!
-It’s a bit weird that the caret starts at the beginning of the selected text (|We’ve confirmed... instead of ...his identity|)
-Maybe rename AlexJS in the hamburger menu to Website (that way people know where they’re going);
-Rename Alex, where it refers to the project (not to the site), to just alex (note the case);
-Maybe, instead of having both License: MIT License in the subtitle and LICENSE in the bottom button bar, opt for MIT License only, and in the button bar?

- The headings in the licenses list are now a light grey, slightly bolder, without the colons, and with a bit of padding; to follow Material Design better.
- I decided to not use semicolons or colons.
- On all sides there is the same amount of padding, it looks funk though because of the title's weird line-height.
![image](https://cloud.githubusercontent.com/assets/5341898/9981584/ea5d934a-5f75-11e5-9b62-20841e21fe9e.png)
- I haven't been able to see this. Could you send a screenshot?
- Done.
- Where? In licenses or the appbar?
- I'm not sure what you mean by `and in the button bar?`

@sindresorhus 
I'm looking to do something very similar as well.

@wooorm @sindresorhus 
It does it by adding `<g>` tags to every area, which only works with contenteditable elements, not inputs. This is why I opted for one in the popup in Alex (instead of the buggy highlighting on the project website). It currently can highlight things by adding `<span>` tags, but when the field is edited, the caret is moved to the beginning and adding on to `<span>` causes all of the following text to appear as an issue. I am trying to fix those things and then I'll copy that code to the page so it can evaluate each contenteditable field.

I'm not sure how I'd do `textarea`s though.

**Comment by danielhickman** [comment] 2015-09-20 16:27
Oh my. I looked at Grammarly's source code, it's 53,000 lines long.

**Comment by danielhickman** [comment] 2015-09-20 18:27
Unlisted Chrome webstore version: https://chrome.google.com/webstore/detail/odeagamimaijfiaeikecldjjajfapmmb

**Comment by wooorm** [comment] 2015-09-20 18:40
@danielhickman I get an error when clicking that link;

1.
2.
3. I meant outside the blocks, between the blocks and the modal;
4. Here: ![screen shot 2015-09-20 at 8 31 45 p m](https://cloud.githubusercontent.com/assets/944406/9982279/ab6ecf44-5fd6-11e5-8b51-27e3e6a2f2b6.png)
5.
6. Both :)
7. I meant don’t list the license next to the author, just in the button bar of the blocks, and instead of having `License` opt for `MIT License` (and others) there.

Also, I tried uninstalling the extension (installed from GH) on Chrome Canary and for some reason it crashes Chrome. Now the hamburger menu doesn’t work + the selection doesn’t come through (see photo above) anymore :/ Maybe that has to do with non-Chrome-Web-Store extensions though!

**Comment by wooorm** [comment] 2015-09-20 18:41
Oh now the link comes through :)

**Comment by danielhickman** [comment] 2015-09-20 23:41
@wooorm 
1.
2.
3. I'm trying to stay as close to Material Design as I can without using their tools, so the 8px each side of the cards is what I'd like. (I'm using 1px = 1dp)
4. I still don't see that with any version. Is the caret there for you when you first open the extension? I didn't make it focus on run (I've disabled that until I fix the highlight) :confused: Also, I see "No issues!" when the sample text is there, is that because of the deletion in Chrome Canary?
5.
6. I don't think it looks as presentable, and it really doesn't look good with a Material Design appbar, I am not sure what to do about it.
7. That makes sense, I might do that but I don't like providing information in actions, it's not as intuitive.
8. That sucks, I removed the non-website version successfully. It probably deleted the JavaScript causing it not to work.

**Comment by meetbryce** [comment] 2015-09-21 00:59
Just an idea, but if you make the background color a light gray color (eg
#f2f2f2) it might look a little more natural.
Cheers,
Bryce York

On Mon, Sep 21, 2015 at 9:41 AM Daniel Hickman <notifications@github.com> wrote:
@wooorm
1.
2.
3. I'm trying to stay as close to Material Design as I can without using their
tools, so the 8px each side of the cards is what I'd like. (I'm using 1px = 1dp)
4. I still don't see that with any version. Is the caret there for you when you
first open the extension? I didn't make it focus on run (I've disabled that
until I fix the highlight) Also, I see "No issues!" when the sample text is there, is that because of the
deletion in Chrome Canary?
5.
6. I don't think it looks as presentable, and it really doesn't look good with a
Material Design appbar, I am not sure what to do about it.
7. That makes sense, I might do that but I don't like providing information in
actions, it's not as intuitive.
8. That sucks, I removed the non-website version successfully. It probably
deleted the JavaScript causing it not to work.

**Comment by meetbryce** [comment] 2015-09-21 01:02
Sorry to double email, but is it possible to have the placeholder text actually
be placeholder text?
Cheers,
Bryce York

On Mon, Sep 21, 2015 at 10:59 AM Bryce York <bryce@meetbryce.com> wrote:
Just an idea, but if you make the background color a light gray color (eg
#f2f2f2) it might look a little more natural.
Cheers,
Bryce York

On Mon, Sep 21, 2015 at 9:41 AM Daniel Hickman < notifications@github.com > wrote:
@wooorm
1.
2.
3. I'm trying to stay as close to Material Design as I can without using their
tools, so the 8px each side of the cards is what I'd like. (I'm using 1px = 1dp)
4. I still don't see that with any version. Is the caret there for you when you
first open the extension? I didn't make it focus on run (I've disabled that
until I fix the highlight) Also, I see "No issues!" when the sample text is there, is that because of the
deletion in Chrome Canary?
5.
6. I don't think it looks as presentable, and it really doesn't look good with a
Material Design appbar, I am not sure what to do about it.
7. That makes sense, I might do that but I don't like providing information in
actions, it's not as intuitive.
8. That sucks, I removed the non-website version successfully. It probably
deleted the JavaScript causing it not to work.

**Comment by wooorm** [comment] 2015-09-21 15:58
@danielhickman Sorry for the late response!

1.
2.
3. I think I’m having trouble getting my point across, I’m talking about the fact that in the below image the green line should be equal in length to the red line:
    ![screen](https://cloud.githubusercontent.com/assets/944406/9996819/337921f2-6089-11e5-8162-40640a1d6417.png)
4. “No issues” is indeed because of the sample text; here’s a screenshot of real text, where the caret still starts at the beginning (whereas I propose it moves to the end):
    ![screen shot 2015-09-21 at 5 52 03 p m](https://cloud.githubusercontent.com/assets/944406/9996887/96c2c3b2-6089-11e5-8318-acf53d3dcab6.png)

5.
6. An alternative is to use upper-case (`ALEX`) in the app bar, but I’d really prefer `AlexJS` in the licenses to be `alex`, and `AlexJS` in the hamburger menu to be `Website` (or `alexjs.com`).
7. Okay;
8. As long as it doesn’t happen with the live version! 😄

Anyway, it’s going really well :) Looking forward to see the `contentEditable` integration! Also, just a counter on a `textArea` is acceptable to me!

**Comment by danielhickman** [comment] 2015-09-24 23:45
@wooorm
I've had "No issues!" in the code before I released it. I added some extra spacing to it just now (not shown in picture).
See: https://cloud.githubusercontent.com/assets/5341898/9981584/ea5d934a-5f75-11e5-9b62-20841e21fe9e.png

I've not been able to add much to it the past few days, pull requests welcome.

**Comment by wooorm** [comment] 2015-09-25 11:55
@danielhickman Cool, I’ll try to look into it over the weekend :+1:

**Comment by wooorm** [comment] 2016-02-03 19:59
@danielhickman, sorry, I totally forgot you worked on this! :anguished: 

Are you still available to continue work on this?

**Comment by danielhickman** [comment] 2016-02-08 01:53
I'll continue working on it. I'm still learning programming so it's a challenge. (I'm 15)

**Comment by kishore-narendran** [comment] 2016-02-09 20:17
Is someone still working on this?

**Comment by wooorm** [comment] 2016-02-09 20:23
@kishore-narendran Pretty evident from the comment before yours, right?

@danielhickman Okay, awesome! So am I! Could you push the code to GH? Can be private, before we publish it, in which case I’m able to provide a private repo if needed.
If the code is somewhere online I can help more :)

**Comment by kishore-narendran** [comment] 2016-02-10 02:05
My apologies @wooorm

**Comment by danielhickman** [comment] 2016-02-13 05:12
@wooorm It's been on GitHub. 

Link: https://github.com/xorprojects/Alex-Chrome-Extension

**Comment by wooorm** [comment] 2016-02-13 12:39
Oh right, I forgot, sorry :)

**Comment by rugk** [comment] 2016-02-17 13:00
Can we also have this extension for Firefox?

**Comment by wooorm** [comment] 2016-02-17 13:30
@rugk If someone makes it

**Comment by wooorm** [comment] 2016-06-29 19:36
Closing as there's no visible work on this. If you're making this, please open a new issue or ask to reopen this!

**Closed by wooorm** 2016-06-29 19:36 UTC
Labels: concept, enhancement, help wanted

**Comment by kishore-narendran** [comment] 2016-06-29 19:45
If no one is making this anymore I'd love to. 

Get Outlook for iOS




On Wed, Jun 29, 2016 at 12:36 PM -0700, "Titus Wormer" <notifications@github.com> wrote:












Closing as there's no visible work on this. If you're making this, please open a new issue or ask to reopen this!

**Comment by rugk** [comment] 2016-06-29 20:18
> If no one is making this anymore I'd love to. 

What exactly? Firefox browser extension? Bookmarklet?

At least I think a bookmarklet would be the easiest and best browser cross-compatible solution. A real add-on can be created afterwards.

**Comment by wooorm** [comment] 2016-06-29 20:55
@kishore-narendran @rugk This issue was originally about a browser extension / bookmarklet. I’d love both, and will add it to the [integrations](https://github.com/wooorm/alex#integrations) 👍

**Comment by kishore-narendran** [comment] 2016-06-29 23:46
@rugk Do you want to make a bookmarklet or a browser extension? 😛 I'll take either.

**Comment by rugk** [comment] 2016-06-30 10:32
At first the thing which is easier to create...
And that's - as I assume - a bookmarklet. As I said the browser extension could be created afterwards...
