### ISSUE TITLE
Alex gives no output when using with stdin.

### ISSUE THREAD

**Issue by sils1297** [wooorm/alex#61] opened 2015-11-20 08:51 UTC
Probably related with https://github.com/wooorm/mdast/issues/90 .

Alex gives no output when using with stdin. Just installed with `npm install --global alex` and executed the example from your help page.

```
lasse@eduroam-1483 ~/prog/coala (git)-[sils/tests] % echo "His network looks good" | alex

lasse@eduroam-1483 ~/prog/coala (git)-[sils/tests] %
```

**Comment by wooorm** [comment] 2015-11-20 08:52
:(

**Comment by sils1297** [comment] 2015-11-20 08:57
FWIW just executing `alex` on its own checks all files in my directory.

**Comment by wooorm** [comment] 2015-11-20 17:07
Hmm, it that case they might not be related after all. I just tried this, and couldn’t reproduce it at all. `alex < example.md` works perfectly for me. So does `echo "His network looks good" | alex`. Both with a clean install:

```txt
🚀  ~: node -v
v5.1.0
🚀  ~: npm -v
3.3.12
🚀  ~: alex --version
1.6.1
```

For some reason there seems to be something right with my system or wrong with yours. Could you try reproducing on another computer / set-up?

P.S., the same goes for wooorm/mdast#90.

**Comment by sils1297** [comment] 2015-11-20 18:35
On fedora:

```
lasse@eduroam-1483 ~/prog/landing (git)-[sils/textchange] % alex

README.md: no issues found
requirements.txt: no issues found
lasse@eduroam-1483 ~/prog/landing (git)-[sils/textchange] % alex --version
1.6.1
lasse@eduroam-1483 ~/prog/landing (git)-[sils/textchange] % npm -v
1.3.6
lasse@eduroam-1483 ~/prog/landing (git)-[sils/textchange] % node -v
v0.10.36
lasse@eduroam-1483 ~/prog/landing (git)-[sils/textchange] % echo "His network looks good" | alex

lasse@eduroam-1483 ~/prog/landing (git)-[sils/textchange] % 
```

**Comment by sils1297** [comment] 2015-11-20 18:40
that's interesting, on arch:

```
lasse@lssteady ~/prog/landing (git)-[master] % alex

README.md: no issues found
requirements.txt: no issues found
lasse@lssteady ~/prog/landing (git)-[master] % alex --version
1.6.1
lasse@lssteady ~/prog/landing (git)-[master] % npm -v
3.4.0
lasse@lssteady ~/prog/landing (git)-[master] % node -v
v5.1.0
lasse@lssteady ~/prog/landing (git)-[master] % echo "His network looks good" | alex

<stdin>
    1:1-1:4  warning  `His` may be insensitive, use `Their`, `Theirs`, `Them` instead

⚠ 1 warning
```

**Comment by wooorm** [comment] 2015-11-20 20:54
Ah, that I can reproduce!

```txt
🚀  ~: npm -v
1.4.28
🚀  ~: node -v
v0.10.40
🚀  ~: alex --version
1.6.1
🚀  ~: echo "His network looks good" | alex
```

Now, I’m seeing an error when installing `alex` on node@0.10:

```txt
npm WARN engine get-stdin@5.0.1: wanted: {"node":">=0.12.0"} (current: {"node":"0.10.40","npm":"1.4.28"})
```

Which, I’m guessing, is exactly this problem you’re seeing.

To be honest, Node@0.10 is pretty “ancient”. So I’m not really interested in putting in the hours to get that working. Also: I confirmed alex is working as expected for node@0.12.

So, I hope this won’t conflict with your setup, but I’m closing this!

**Closed by wooorm** 2015-11-20 20:54 UTC

**Comment by sils1297** [comment] 2015-11-20 21:24
Sure, note that this is apparently the current node version on Fedora which is usually even newer than what's shipped on RHEL or SLES (Red Hat/Suse Enterprise Linuxes).

**Comment by sils1297** [comment] 2015-11-20 21:28
Ubuntu and especially debian might linger also at that kind of versions. https://apps.fedoraproject.org/packages/nodejs , https://packages.debian.org/stable/nodejs

**Comment by sils1297** [comment] 2015-11-20 21:31
That said, I can totally see you deciding against support for this but if it's not a lot of work it might be highly relevant for a lot of users, apparently.

**Comment by wooorm** [comment] 2015-11-20 21:36
Yeah, I can imagine. Getting it to work wouldn’t be very hard but it would mean [downgrading a dependency](https://github.com/sindresorhus/get-stdin/commit/385a9ce4b44e9311158d58de14e919b67f45b638), meaning it won’t get updates/fixes which is quite the deal.

Sucks those distros don‘t update their node versions. :anguished:

**Comment by sils1297** [comment] 2015-11-20 21:37
I wonder *why* that is, the version number sounds really *really* ancient. I don't see any reason why the major distributions wouldn't ship new versions.

**Comment by sils1297** [comment] 2015-11-20 21:40
Ok I know something that should help you: https://www.digitalocean.com/community/tutorials/how-to-install-node-js-on-an-ubuntu-14-04-server

There's probably a similar tutorialish thing for fedora/RHEL SUSE/SLES so you could just add a few guides for people using those distributions.

**Comment by sils1297** [comment] 2015-11-20 21:41
The nvm method seems to be fairly distribution independent.

**Comment by wooorm** [comment] 2015-11-20 21:44
I’m guessing that to be the most viable cross-OS option!
